import type { DemoItem } from '../../types.ts'
export const THREEUI_EXPORTS = [
  { exportName: 'AmberHalftone', zh: '琥珀半调' },
  { exportName: 'AnimatedTopDock', zh: '顶部坞' },
  { exportName: 'AudioWordmark', zh: '音频字标' },
  { exportName: 'BallStudy', zh: '球体研究' },
  { exportName: 'BellFieldBackground', zh: '钟形场' },
  { exportName: 'BestsellersBookShowcase', zh: '畅销书橱窗' },
  { exportName: 'BookshelfScene', zh: '书架场景' },
  { exportName: 'BrandOrbs', zh: '品牌光球' },
  { exportName: 'CharacterCarousel', zh: '角色轮播' },
  { exportName: 'CharacterFilmstrip', zh: '角色胶片' },
  { exportName: 'CharacterWave', zh: '角色波浪' },
  { exportName: 'CircleButtons', zh: '圆形按钮' },
  { exportName: 'ClothStudy', zh: '布料研究' },
  { exportName: 'CloudField', zh: '云场' },
  { exportName: 'CompleteShelfLandingPage', zh: '完整货架页' },
  { exportName: 'CondensationBackground', zh: '冷凝背景' },
  { exportName: 'ConnectivityGraph', zh: '连接图' },
  { exportName: 'ConstellationField', zh: '星座场' },
  { exportName: 'CrtBackground', zh: 'CRT 背景' },
  { exportName: 'DataField', zh: '数据场' },
  { exportName: 'DefenseLines', zh: '防线' },
  { exportName: 'DiagnosticsPanel', zh: '诊断面板' },
  { exportName: 'DimensionalField', zh: '维度场' },
  { exportName: 'DotBorderButton', zh: '点阵边框按钮' },
  { exportName: 'DotMatrixBackground', zh: '点阵背景' },
  { exportName: 'ElementsBackground', zh: '元素背景' },
  { exportName: 'ElementsCollection', zh: '元素合集' },
  { exportName: 'EmberStorm', zh: '余烬风暴' },
  { exportName: 'EmeraldHorizonBackground', zh: '翡翠地平线' },
  { exportName: 'EngravedCertificate', zh: '雕刻证书' },
  { exportName: 'ExpanseField', zh: '广袤场' },
  { exportName: 'FloatingDotsCta', zh: '漂浮点 CTA' },
  { exportName: 'FlowField', zh: '流场' },
  { exportName: 'FluidFieldBackground', zh: '流体场' },
  { exportName: 'FluxVortex', zh: '通量漩涡' },
  { exportName: 'Gallery', zh: '画廊' },
  { exportName: 'GalleryHeading', zh: '画廊标题' },
  { exportName: 'GatewayFlow', zh: '门户流' },
  { exportName: 'GenerateButton', zh: '生成按钮' },
  { exportName: 'GenerativeTree', zh: '生成树' },
  { exportName: 'GlassmorphismCta', zh: '玻璃拟态 CTA' },
  { exportName: 'GlobeCollection', zh: '地球合集' },
  { exportName: 'GradientBeamCta', zh: '渐变光束 CTA' },
  { exportName: 'GradientCta', zh: '渐变 CTA' },
  { exportName: 'GradientPillButton', zh: '渐变胶囊按钮' },
  { exportName: 'HalftoneFlow', zh: '半调流' },
  { exportName: 'IgnitionButton', zh: '点火按钮' },
  { exportName: 'InductionButton', zh: '感应按钮' },
  { exportName: 'InterfaceLines', zh: '界面线' },
  { exportName: 'JapaneseTowerLandscape', zh: '塔景' },
  { exportName: 'KageLandingPage', zh: '影落地页' },
  { exportName: 'KoiStudies', zh: '锦鲤研究' },
  { exportName: 'LandscapeScene', zh: '风景场景' },
  { exportName: 'LaserCollection', zh: '激光合集' },
  { exportName: 'LaunchButton', zh: '发射按钮' },
  { exportName: 'LiquidFormBackground', zh: '液态形态' },
  { exportName: 'LiquidMetalButton', zh: '液态金属按钮' },
  { exportName: 'LogicCoreField', zh: '逻辑核心场' },
  { exportName: 'LumenCta', zh: '流明 CTA' },
  { exportName: 'MengToSketchbookLandingPage', zh: '速写本落地页' },
  { exportName: 'MorphingGlyphCloud', zh: '字形云' },
  { exportName: 'NebulaBackground', zh: '星云背景' },
  { exportName: 'NeonTypography', zh: '霓虹字体' },
  { exportName: 'OrbitalSphereBackground', zh: '轨道球体' },
  { exportName: 'OutlineTypeflow', zh: '轮廓字流' },
  { exportName: 'ParticleDrift', zh: '粒子漂移' },
  { exportName: 'ParticleNetwork', zh: '粒子网络' },
  { exportName: 'ParticleWordmark', zh: '粒子字标' },
  { exportName: 'PerformanceGauges', zh: '性能仪表' },
  { exportName: 'PlasmaButton', zh: '等离子按钮' },
  { exportName: 'PortalFieldCollection', zh: '传送门场' },
  { exportName: 'PredictiveArcCanvas', zh: '预测弧' },
  { exportName: 'RectangleButtons', zh: '矩形按钮' },
  { exportName: 'RibbonFieldBackground', zh: '缎带场' },
  { exportName: 'RippleStudy', zh: '涟漪研究' },
  { exportName: 'SemanticBloom', zh: '语义绽放' },
  { exportName: 'ShaderButtons', zh: '着色器按钮' },
  { exportName: 'Sketchbook', zh: '速写本' },
  { exportName: 'SkeuomorphicToggle', zh: '拟物开关' },
  { exportName: 'SlidingTextCta', zh: '滑动文字 CTA' },
  { exportName: 'SparkBadge', zh: '火花徽章' },
  { exportName: 'SpinningBorderButton', zh: '旋转边框按钮' },
  { exportName: 'StreamConvergenceBackground', zh: '流汇聚' },
  { exportName: 'StructureFlowCollection', zh: '结构流' },
  { exportName: 'SylvaHero', zh: '希尔瓦主视觉' },
  { exportName: 'SylvaLivingWorldScene', zh: '希尔瓦世界' },
  { exportName: 'TactileButton', zh: '触觉按钮' },
  { exportName: 'TempleNightScene', zh: '夜寺' },
  { exportName: 'TextAnimationCollection', zh: '文字动画合集' },
  { exportName: 'TextPathStudies', zh: '文字路径' },
  { exportName: 'ThinkingButton', zh: '思考按钮' },
  { exportName: 'ThreeUIIntro', zh: 'ThreeUI 介绍' },
  { exportName: 'TopoField', zh: '地形场' },
  { exportName: 'TopologyField', zh: '拓扑场' },
  { exportName: 'TypographyVortexCanvas', zh: '字体漩涡' },
  { exportName: 'UplinkLoader', zh: '上行加载' },
  { exportName: 'VoidField', zh: '虚空场' },
  { exportName: 'WarpFieldBackground', zh: '扭曲场' },
  { exportName: 'WireframeForms', zh: '线框形体' },
  { exportName: 'WovenCloth', zh: '编织布' },
] as const

export const threeuiDemos: DemoItem[] = THREEUI_EXPORTS.map((item) => ({
  id: `threeui-${item.exportName}`,
  source: 'threeui',
  name: item.exportName,
  zh: item.zh,
  en: item.exportName,
  webgl: true,
  code: `import { ${item.exportName} } from '@designcodeio/threeui/components/${item.exportName}'\n\nexport function Preview() {\n  return (\n    <div className=\"stage\">\n      <${item.exportName} sourceUrl=\"/\" assetBaseUrl=\"/\" />\n    </div>\n  )\n}\n`,
}))
