import type { DemoItem } from '../../types.ts'

export type RbMeta = {
  name: string
  childrenKind: string | null
  defaults: Record<string, unknown>
  webgl: boolean
}

export const RB_META: Record<string, RbMeta> = {
  ASCIIText: { name: "ASCIIText", childrenKind: null, defaults: {"text": "ASCII 文字"}, webgl: true },
  AccordionGallery: { name: "AccordionGallery", childrenKind: null, defaults: {"items": ["手风琴画廊 1", "手风琴画廊 2", "手风琴画廊 3", "手风琴画廊 4"]}, webgl: false },
  AcidSquares: { name: "AcidSquares", childrenKind: null, defaults: {}, webgl: true },
  AnimatedContent: { name: "AnimatedContent", childrenKind: "tile", defaults: {}, webgl: false },
  AnimatedList: { name: "AnimatedList", childrenKind: "tile", defaults: {}, webgl: false },
  Antigravity: { name: "Antigravity", childrenKind: null, defaults: {}, webgl: true },
  Aurora: { name: "Aurora", childrenKind: null, defaults: {"color": "#6366f1"}, webgl: true },
  Balatro: { name: "Balatro", childrenKind: null, defaults: {}, webgl: true },
  Ballpit: { name: "Ballpit", childrenKind: null, defaults: {}, webgl: true },
  Beams: { name: "Beams", childrenKind: "tile", defaults: {"color": "#6366f1"}, webgl: true },
  BlobCursor: { name: "BlobCursor", childrenKind: null, defaults: {}, webgl: false },
  BlurText: { name: "BlurText", childrenKind: null, defaults: {"text": "模糊显现"}, webgl: false },
  BorderGlow: { name: "BorderGlow", childrenKind: "tile", defaults: {}, webgl: true },
  BounceCards: { name: "BounceCards", childrenKind: null, defaults: {"images": ["/ph/1.svg", "/ph/2.svg", "/ph/3.svg", "/ph/4.svg"]}, webgl: false },
  BubbleMenu: { name: "BubbleMenu", childrenKind: null, defaults: {"items": ["气泡菜单 1", "气泡菜单 2", "气泡菜单 3", "气泡菜单 4"]}, webgl: false },
  CardNav: { name: "CardNav", childrenKind: null, defaults: {"items": ["卡片导航 1", "卡片导航 2", "卡片导航 3", "卡片导航 4"]}, webgl: false },
  CardSwap: { name: "CardSwap", childrenKind: "tile", defaults: {}, webgl: false },
  Carousel: { name: "Carousel", childrenKind: null, defaults: {}, webgl: false },
  ChromaGrid: { name: "ChromaGrid", childrenKind: null, defaults: {"items": [{"image": "/ph/1.svg", "title": "项目 1", "subtitle": "react-bits", "borderColor": "#6366f1", "url": "#"}, {"image": "/ph/2.svg", "title": "项目 2", "subtitle": "react-bits", "borderColor": "#6366f1", "url": "#"}, {"image": "/ph/3.svg", "title": "项目 3", "subtitle": "react-bits", "borderColor": "#6366f1", "url": "#"}, {"image": "/ph/4.svg", "title": "项目 4", "subtitle": "react-bits", "borderColor": "#6366f1", "url": "#"}, {"image": "/ph/1.svg", "title": "项目 5", "subtitle": "react-bits", "borderColor": "#6366f1", "url": "#"}, {"image": "/ph/2.svg", "title": "项目 6", "subtitle": "react-bits", "borderColor": "#6366f1", "url": "#"}]}, webgl: false },
  CircularGallery: { name: "CircularGallery", childrenKind: null, defaults: {"items": ["环形画廊 1", "环形画廊 2", "环形画廊 3", "环形画廊 4"]}, webgl: true },
  CircularText: { name: "CircularText", childrenKind: null, defaults: {"text": "官方组件 · 运动实验室 · "}, webgl: false },
  ClickSpark: { name: "ClickSpark", childrenKind: "tile", defaults: {}, webgl: false },
  ColorBends: { name: "ColorBends", childrenKind: null, defaults: {}, webgl: true },
  CountUp: { name: "CountUp", childrenKind: null, defaults: {"to": 2026, "from": 0, "duration": 2}, webgl: false },
  Counter: { name: "Counter", childrenKind: null, defaults: {}, webgl: false },
  Crosshair: { name: "Crosshair", childrenKind: "tile", defaults: {}, webgl: false },
  Cubes: { name: "Cubes", childrenKind: null, defaults: {}, webgl: false },
  CursorGrid: { name: "CursorGrid", childrenKind: null, defaults: {}, webgl: false },
  CurvedInput: { name: "CurvedInput", childrenKind: null, defaults: {}, webgl: false },
  CurvedLoop: { name: "CurvedLoop", childrenKind: null, defaults: {"marqueeText": "数学曲线 · 官方组件 · "}, webgl: false },
  DarkVeil: { name: "DarkVeil", childrenKind: null, defaults: {}, webgl: true },
  DecayCard: { name: "DecayCard", childrenKind: "tile", defaults: {}, webgl: false },
  DecryptedText: { name: "DecryptedText", childrenKind: null, defaults: {"text": "解密文字"}, webgl: false },
  DepthCarousel: { name: "DepthCarousel", childrenKind: null, defaults: {"items": ["纵深轮播 1", "纵深轮播 2", "纵深轮播 3", "纵深轮播 4"]}, webgl: false },
  DepthText: { name: "DepthText", childrenKind: null, defaults: {"text": "纵深文字"}, webgl: false },
  Dither: { name: "Dither", childrenKind: null, defaults: {}, webgl: true },
  Dock: { name: "Dock", childrenKind: "tile", defaults: {"label": "程序坞", "items": [{"icon": "A", "label": "一"}, {"icon": "B", "label": "二"}, {"icon": "C", "label": "三"}]}, webgl: false },
  DomeGallery: { name: "DomeGallery", childrenKind: null, defaults: {"images": ["/ph/1.svg", "/ph/2.svg", "/ph/3.svg", "/ph/4.svg"]}, webgl: false },
  DotField: { name: "DotField", childrenKind: null, defaults: {}, webgl: false },
  DotGrid: { name: "DotGrid", childrenKind: null, defaults: {}, webgl: false },
  DriftWall: { name: "DriftWall", childrenKind: null, defaults: {"items": ["漂移墙 1", "漂移墙 2", "漂移墙 3", "漂移墙 4"]}, webgl: false },
  EchoText: { name: "EchoText", childrenKind: null, defaults: {"text": "回声文字"}, webgl: false },
  ElasticMesh: { name: "ElasticMesh", childrenKind: null, defaults: {}, webgl: true },
  ElasticSlider: { name: "ElasticSlider", childrenKind: "tile", defaults: {}, webgl: false },
  ElectricBorder: { name: "ElectricBorder", childrenKind: "tile", defaults: {}, webgl: false },
  EvilEye: { name: "EvilEye", childrenKind: null, defaults: {}, webgl: true },
  FadeContent: { name: "FadeContent", childrenKind: "tile", defaults: {}, webgl: false },
  FallingText: { name: "FallingText", childrenKind: null, defaults: {"text": "坠落文字"}, webgl: false },
  FaultyTerminal: { name: "FaultyTerminal", childrenKind: null, defaults: {}, webgl: true },
  Ferrofluid: { name: "Ferrofluid", childrenKind: null, defaults: {}, webgl: true },
  FloatingLines: { name: "FloatingLines", childrenKind: null, defaults: {}, webgl: true },
  FlowingMenu: { name: "FlowingMenu", childrenKind: null, defaults: {"items": ["流动菜单 1", "流动菜单 2", "流动菜单 3", "流动菜单 4"]}, webgl: false },
  FluidGlass: { name: "FluidGlass", childrenKind: null, defaults: {}, webgl: true },
  FlyingPosters: { name: "FlyingPosters", childrenKind: null, defaults: {"items": ["飞行海报 1", "飞行海报 2", "飞行海报 3", "飞行海报 4"]}, webgl: true },
  FoldText: { name: "FoldText", childrenKind: null, defaults: {"text": "折纸文字"}, webgl: false },
  Folder: { name: "Folder", childrenKind: "tile", defaults: {"items": ["文件夹 1", "文件夹 2", "文件夹 3", "文件夹 4"]}, webgl: false },
  FuzzyText: { name: "FuzzyText", childrenKind: null, defaults: {}, webgl: false },
  Galaxy: { name: "Galaxy", childrenKind: null, defaults: {"color": "#6366f1"}, webgl: true },
  GhostCursor: { name: "GhostCursor", childrenKind: null, defaults: {}, webgl: true },
  GlareHover: { name: "GlareHover", childrenKind: "tile", defaults: {}, webgl: false },
  GlassIcons: { name: "GlassIcons", childrenKind: null, defaults: {"items": ["玻璃图标 1", "玻璃图标 2", "玻璃图标 3", "玻璃图标 4"]}, webgl: false },
  GlassSurface: { name: "GlassSurface", childrenKind: "tile", defaults: {}, webgl: false },
  GlitchText: { name: "GlitchText", childrenKind: null, defaults: {}, webgl: false },
  GooeyNav: { name: "GooeyNav", childrenKind: null, defaults: {"items": [{"label": "首页", "href": "#"}, {"label": "画廊", "href": "#"}, {"label": "关于", "href": "#"}]}, webgl: false },
  GradientBlinds: { name: "GradientBlinds", childrenKind: null, defaults: {}, webgl: true },
  GradientText: { name: "GradientText", childrenKind: "text", defaults: {}, webgl: false },
  GradientWaves: { name: "GradientWaves", childrenKind: null, defaults: {}, webgl: true },
  GradualBlur: { name: "GradualBlur", childrenKind: "tile", defaults: {}, webgl: false },
  Grainient: { name: "Grainient", childrenKind: null, defaults: {}, webgl: true },
  GridDistortion: { name: "GridDistortion", childrenKind: null, defaults: {}, webgl: true },
  GridMotion: { name: "GridMotion", childrenKind: null, defaults: {"items": ["网格运动 1", "网格运动 2", "网格运动 3", "网格运动 4"]}, webgl: false },
  GridScan: { name: "GridScan", childrenKind: null, defaults: {}, webgl: true },
  HalftoneReveal: { name: "HalftoneReveal", childrenKind: "tile", defaults: {}, webgl: true },
  Hyperspeed: { name: "Hyperspeed", childrenKind: null, defaults: {}, webgl: true },
  ImageTrail: { name: "ImageTrail", childrenKind: null, defaults: {"items": ["图像拖尾 1", "图像拖尾 2", "图像拖尾 3", "图像拖尾 4"]}, webgl: false },
  InfiniteMenu: { name: "InfiniteMenu", childrenKind: null, defaults: {"items": ["无限菜单 1", "无限菜单 2", "无限菜单 3", "无限菜单 4"]}, webgl: true },
  Iridescence: { name: "Iridescence", childrenKind: null, defaults: {}, webgl: true },
  Lanyard: { name: "Lanyard", childrenKind: null, defaults: {}, webgl: true },
  LaserFlow: { name: "LaserFlow", childrenKind: null, defaults: {}, webgl: true },
  LetterGlitch: { name: "LetterGlitch", childrenKind: null, defaults: {}, webgl: false },
  LightPillar: { name: "LightPillar", childrenKind: null, defaults: {}, webgl: true },
  LightRays: { name: "LightRays", childrenKind: null, defaults: {}, webgl: true },
  LightTunnel: { name: "LightTunnel", childrenKind: null, defaults: {}, webgl: true },
  Lightfall: { name: "Lightfall", childrenKind: null, defaults: {}, webgl: true },
  Lightning: { name: "Lightning", childrenKind: null, defaults: {}, webgl: true },
  LineSidebar: { name: "LineSidebar", childrenKind: null, defaults: {"items": ["线型侧栏 1", "线型侧栏 2", "线型侧栏 3", "线型侧栏 4"]}, webgl: false },
  LineWaves: { name: "LineWaves", childrenKind: null, defaults: {}, webgl: true },
  LiquidChrome: { name: "LiquidChrome", childrenKind: null, defaults: {}, webgl: true },
  LiquidEther: { name: "LiquidEther", childrenKind: null, defaults: {}, webgl: true },
  LogoLoop: { name: "LogoLoop", childrenKind: null, defaults: {}, webgl: false },
  MagicBento: { name: "MagicBento", childrenKind: "tile", defaults: {}, webgl: false },
  MagicRings: { name: "MagicRings", childrenKind: null, defaults: {}, webgl: true },
  Magnet: { name: "Magnet", childrenKind: "button", defaults: {}, webgl: false },
  MagnetLines: { name: "MagnetLines", childrenKind: null, defaults: {}, webgl: false },
  MaskedHeading: { name: "MaskedHeading", childrenKind: null, defaults: {"text": "蒙版标题"}, webgl: false },
  Masonry: { name: "Masonry", childrenKind: null, defaults: {"items": ["瀑布流 1", "瀑布流 2", "瀑布流 3", "瀑布流 4"]}, webgl: false },
  MetaBalls: { name: "MetaBalls", childrenKind: null, defaults: {}, webgl: true },
  MetallicPaint: { name: "MetallicPaint", childrenKind: null, defaults: {}, webgl: true },
  ModelViewer: { name: "ModelViewer", childrenKind: null, defaults: {}, webgl: true },
  MoltenMetal: { name: "MoltenMetal", childrenKind: null, defaults: {}, webgl: true },
  MorphSlider: { name: "MorphSlider", childrenKind: null, defaults: {"items": ["熔变滑块 1", "熔变滑块 2", "熔变滑块 3", "熔变滑块 4"]}, webgl: true },
  Noise: { name: "Noise", childrenKind: null, defaults: {}, webgl: false },
  OptionWheel: { name: "OptionWheel", childrenKind: null, defaults: {"items": ["选项轮 1", "选项轮 2", "选项轮 3", "选项轮 4"]}, webgl: false },
  Orb: { name: "Orb", childrenKind: null, defaults: {}, webgl: true },
  OrbitImages: { name: "OrbitImages", childrenKind: null, defaults: {}, webgl: false },
  ParticleText: { name: "ParticleText", childrenKind: null, defaults: {"text": "粒子文字"}, webgl: false },
  Particles: { name: "Particles", childrenKind: null, defaults: {"color": "#6366f1"}, webgl: true },
  PillNav: { name: "PillNav", childrenKind: null, defaults: {"items": [{"label": "首页", "href": "#"}, {"label": "组件", "href": "#"}]}, webgl: false },
  PixelBlast: { name: "PixelBlast", childrenKind: null, defaults: {}, webgl: true },
  PixelCard: { name: "PixelCard", childrenKind: "tile", defaults: {}, webgl: false },
  PixelSnow: { name: "PixelSnow", childrenKind: null, defaults: {}, webgl: true },
  PixelSwap: { name: "PixelSwap", childrenKind: "tile", defaults: {}, webgl: false },
  PixelTrail: { name: "PixelTrail", childrenKind: null, defaults: {}, webgl: true },
  PixelTransition: { name: "PixelTransition", childrenKind: "tile", defaults: {}, webgl: false },
  Plasma: { name: "Plasma", childrenKind: null, defaults: {"color": "#6366f1"}, webgl: true },
  PlasmaWave: { name: "PlasmaWave", childrenKind: null, defaults: {}, webgl: true },
  Prism: { name: "Prism", childrenKind: null, defaults: {}, webgl: true },
  PrismaticBurst: { name: "PrismaticBurst", childrenKind: null, defaults: {}, webgl: true },
  ProfileCard: { name: "ProfileCard", childrenKind: null, defaults: {"title": "资料卡"}, webgl: false },
  Radar: { name: "Radar", childrenKind: null, defaults: {}, webgl: true },
  ReflectiveCard: { name: "ReflectiveCard", childrenKind: "tile", defaults: {}, webgl: false },
  Ribbons: { name: "Ribbons", childrenKind: null, defaults: {}, webgl: true },
  RippleDistortion: { name: "RippleDistortion", childrenKind: "tile", defaults: {}, webgl: true },
  RippleGrid: { name: "RippleGrid", childrenKind: null, defaults: {}, webgl: true },
  RotatingText: { name: "RotatingText", childrenKind: null, defaults: {"texts": ["运动", "实验室", "前端"]}, webgl: false },
  Scanner: { name: "Scanner", childrenKind: null, defaults: {}, webgl: true },
  ScrambledText: { name: "ScrambledText", childrenKind: null, defaults: {}, webgl: false },
  ScrollExpand: { name: "ScrollExpand", childrenKind: "tile", defaults: {"title": "滚动扩展"}, webgl: false },
  ScrollFloat: { name: "ScrollFloat", childrenKind: null, defaults: {}, webgl: false },
  ScrollReveal: { name: "ScrollReveal", childrenKind: null, defaults: {}, webgl: false },
  ScrollStack: { name: "ScrollStack", childrenKind: "tile", defaults: {}, webgl: false },
  ScrollVelocity: { name: "ScrollVelocity", childrenKind: null, defaults: {"texts": ["滚动速度字", "运动实验室", "官方组件"]}, webgl: false },
  ShapeBlur: { name: "ShapeBlur", childrenKind: null, defaults: {}, webgl: true },
  ShapeGrid: { name: "ShapeGrid", childrenKind: null, defaults: {}, webgl: false },
  ShinyText: { name: "ShinyText", childrenKind: null, defaults: {"text": "金属扫光字"}, webgl: false },
  Shuffle: { name: "Shuffle", childrenKind: null, defaults: {"text": "洗牌文字"}, webgl: false },
  SideRays: { name: "SideRays", childrenKind: null, defaults: {}, webgl: true },
  Silk: { name: "Silk", childrenKind: null, defaults: {"color": "#6366f1"}, webgl: true },
  SlicedWaves: { name: "SlicedWaves", childrenKind: null, defaults: {}, webgl: true },
  SoftAurora: { name: "SoftAurora", childrenKind: null, defaults: {}, webgl: true },
  SpecularButton: { name: "SpecularButton", childrenKind: "tile", defaults: {}, webgl: true },
  SplashCursor: { name: "SplashCursor", childrenKind: null, defaults: {}, webgl: true },
  SplitFlapText: { name: "SplitFlapText", childrenKind: null, defaults: {"text": "FX-LAB", "words": ["运动", "实验室", "官方", "组件"]}, webgl: false },
  SplitText: { name: "SplitText", childrenKind: null, defaults: {"text": "拆分文字"}, webgl: false },
  SpotlightCard: { name: "SpotlightCard", childrenKind: "tile", defaults: {}, webgl: false },
  Stack: { name: "Stack", childrenKind: "tile", defaults: {}, webgl: false },
  StaggeredMenu: { name: "StaggeredMenu", childrenKind: null, defaults: {"items": ["交错菜单 1", "交错菜单 2", "交错菜单 3", "交错菜单 4"]}, webgl: false },
  StarBorder: { name: "StarBorder", childrenKind: "tile", defaults: {}, webgl: false },
  Stepper: { name: "Stepper", childrenKind: "tile", defaults: {}, webgl: false },
  StickerPeel: { name: "StickerPeel", childrenKind: "tile", defaults: {}, webgl: false },
  Strands: { name: "Strands", childrenKind: null, defaults: {}, webgl: true },
  StrokeText: { name: "StrokeText", childrenKind: null, defaults: {"text": "描边文字"}, webgl: false },
  SwarmCursor: { name: "SwarmCursor", childrenKind: "tile", defaults: {}, webgl: true },
  TargetCursor: { name: "TargetCursor", childrenKind: "tile", defaults: {}, webgl: false },
  TextCursor: { name: "TextCursor", childrenKind: null, defaults: {"text": "文字光标"}, webgl: false },
  TextLoop: { name: "TextLoop", childrenKind: null, defaults: {"text": "文字循环"}, webgl: false },
  TextPressure: { name: "TextPressure", childrenKind: null, defaults: {"text": "压力文字"}, webgl: true },
  TextType: { name: "TextType", childrenKind: null, defaults: {"text": ["正在输入官方组件", "react-bits"]}, webgl: false },
  Threads: { name: "Threads", childrenKind: null, defaults: {"color": "#6366f1"}, webgl: true },
  TiltedCard: { name: "TiltedCard", childrenKind: "tile", defaults: {}, webgl: false },
  Topography: { name: "Topography", childrenKind: null, defaults: {}, webgl: true },
  TrueFocus: { name: "TrueFocus", childrenKind: null, defaults: {"sentence": "官方 组件 实时 预览"}, webgl: false },
  VariableProximity: { name: "VariableProximity", childrenKind: null, defaults: {}, webgl: false },
  WarpText: { name: "WarpText", childrenKind: null, defaults: {}, webgl: true },
  Waves: { name: "Waves", childrenKind: null, defaults: {"color": "#6366f1"}, webgl: false },
  WebThreads: { name: "WebThreads", childrenKind: null, defaults: {}, webgl: true },
}

const ZH: Record<string, string> = {
  ASCIIText: "ASCII 文字",
  AccordionGallery: "手风琴画廊",
  AcidSquares: "酸性方块",
  AnimatedContent: "内容入场",
  AnimatedList: "交错列表",
  Antigravity: "反重力粒子",
  Aurora: "极光背景",
  Balatro: "Balatro 着色",
  Ballpit: "球池",
  Beams: "光束",
  BlobCursor: "液态光标",
  BlurText: "模糊显现",
  BorderGlow: "边框辉光",
  BounceCards: "弹跳卡片",
  BubbleMenu: "气泡菜单",
  CardNav: "卡片导航",
  CardSwap: "卡片交换",
  Carousel: "轮播",
  ChromaGrid: "色度网格",
  CircularGallery: "环形画廊",
  CircularText: "环形文字",
  ClickSpark: "点击火花",
  ColorBends: "色彩弯折",
  CountUp: "数字递增",
  Counter: "计数器",
  Crosshair: "准星光标",
  Cubes: "立方体簇",
  CursorGrid: "光标网格",
  CurvedInput: "弧形输入",
  CurvedLoop: "曲线循环字",
  DarkVeil: "暗幕",
  DecayCard: "消散卡片",
  DecryptedText: "解密文字",
  DepthCarousel: "纵深轮播",
  DepthText: "纵深文字",
  Dither: "抖动背景",
  Dock: "程序坞",
  DomeGallery: "穹顶画廊",
  DotField: "点阵场",
  DotGrid: "点阵网格",
  DriftWall: "漂移墙",
  EchoText: "回声文字",
  ElasticMesh: "弹性网格",
  ElasticSlider: "弹性滑块",
  ElectricBorder: "电弧边框",
  EvilEye: "邪眼",
  FadeContent: "淡入内容",
  FallingText: "坠落文字",
  FaultyTerminal: "故障终端",
  Ferrofluid: "磁流体",
  FloatingLines: "漂浮线",
  FlowingMenu: "流动菜单",
  FluidGlass: "流体玻璃",
  FlyingPosters: "飞行海报",
  FoldText: "折纸文字",
  Folder: "文件夹",
  FuzzyText: "毛刺文字",
  Galaxy: "星系",
  GhostCursor: "幽灵光标",
  GlareHover: "眩光悬停",
  GlassIcons: "玻璃图标",
  GlassSurface: "玻璃表面",
  GlitchText: "故障文字",
  GooeyNav: "粘滞导航",
  GradientBlinds: "渐变百叶",
  GradientText: "渐变文字",
  GradientWaves: "渐变波",
  GradualBlur: "渐进去模糊",
  Grainient: "颗粒渐变",
  GridDistortion: "网格畸变",
  GridMotion: "网格运动",
  GridScan: "网格扫描",
  HalftoneReveal: "半调显现",
  Hyperspeed: "超空间",
  ImageTrail: "图像拖尾",
  InfiniteMenu: "无限菜单",
  Iridescence: "虹彩",
  Lanyard: "挂绳工牌",
  LaserFlow: "激光流",
  LetterGlitch: "字母故障",
  LightPillar: "光柱",
  LightRays: "体积光",
  LightTunnel: "光隧道",
  Lightfall: "光雨",
  Lightning: "闪电",
  LineSidebar: "线型侧栏",
  LineWaves: "线波",
  LiquidChrome: "液态铬",
  LiquidEther: "液态以太",
  LogoLoop: "标志循环",
  MagicBento: "魔法便当格",
  MagicRings: "魔法环",
  Magnet: "磁力吸附",
  MagnetLines: "磁力线",
  MaskedHeading: "蒙版标题",
  Masonry: "瀑布流",
  MetaBalls: "融球",
  MetallicPaint: "金属油漆",
  ModelViewer: "模型查看器",
  MoltenMetal: "熔金",
  MorphSlider: "熔变滑块",
  Noise: "胶片噪点",
  OptionWheel: "选项轮",
  Orb: "能量球",
  OrbitImages: "轨道图像",
  ParticleText: "粒子文字",
  Particles: "粒子场",
  PillNav: "胶囊导航",
  PixelBlast: "像素爆破",
  PixelCard: "像素卡片",
  PixelSnow: "像素雪",
  PixelSwap: "像素交换",
  PixelTrail: "像素拖尾",
  PixelTransition: "像素过渡",
  Plasma: "等离子",
  PlasmaWave: "等离子波",
  Prism: "棱镜",
  PrismaticBurst: "棱镜爆发",
  ProfileCard: "资料卡",
  Radar: "雷达",
  ReflectiveCard: "反射卡片",
  Ribbons: "缎带",
  RippleDistortion: "涟漪畸变",
  RippleGrid: "涟漪网格",
  RotatingText: "旋转文字",
  Scanner: "扫描带",
  ScrambledText: "扰动文字",
  ScrollExpand: "滚动扩展",
  ScrollFloat: "滚动漂浮",
  ScrollReveal: "滚动显现",
  ScrollStack: "滚动堆叠",
  ScrollVelocity: "滚动速度字",
  ShapeBlur: "形状模糊",
  ShapeGrid: "形状网格",
  ShinyText: "金属扫光字",
  Shuffle: "洗牌文字",
  SideRays: "侧向光",
  Silk: "丝绸",
  SlicedWaves: "切片波",
  SoftAurora: "柔和极光",
  SpecularButton: "高光按钮",
  SplashCursor: "飞溅光标",
  SplitFlapText: "翻牌文字",
  SplitText: "拆分文字",
  SpotlightCard: "聚光卡片",
  Stack: "层叠卡片",
  StaggeredMenu: "交错菜单",
  StarBorder: "星光边框",
  Stepper: "步骤条",
  StickerPeel: "贴纸揭起",
  Strands: "光丝",
  StrokeText: "描边文字",
  SwarmCursor: "蜂群光标",
  TargetCursor: "锁定光标",
  TextCursor: "文字光标",
  TextLoop: "文字循环",
  TextPressure: "压力文字",
  TextType: "打字机",
  Threads: "织线",
  TiltedCard: "倾斜卡片",
  Topography: "等高线",
  TrueFocus: "真焦点",
  VariableProximity: "近距变体字",
  WarpText: "扭曲文字",
  Waves: "波浪线",
  WebThreads: "蛛网丝",
}

export const reactbitsDemos: DemoItem[] = Object.values(RB_META).map((item) => {
  const usage = buildUsage(item)
  return {
    id: `rb-${item.name}`,
    source: 'react-bits',
    name: item.name,
    zh: ZH[item.name] || item.name,
    en: item.name,
    webgl: item.webgl,
    code: usage,
  }
})

function buildUsage(item: RbMeta): string {
  const props = Object.entries(item.defaults)
    .map(([k, v]) => `  ${k}={${JSON.stringify(v)}}`)
    .join('\n')
  const child =
    item.childrenKind === 'button'
      ? '  <button type="button">磁力按钮</button>'
      : item.childrenKind === 'text'
        ? '  渐变文字'
        : item.childrenKind === 'tile'
          ? '  <div className="demo-tile">官方组件</div>'
          : ''
  const inner = [props, child].filter(Boolean).join('\n')
  return `import ${item.name} from '@/react-bits/${item.name}/${item.name}.jsx'\n\nexport function Preview() {\n  return (\n    <${item.name}${inner ? `\n${inner}\n    ` : ' '}/>\n  )\n}\n`
}
